name: Docker CI Pipeline on Windows

on:
  push:
    branches:
      - main  # Trigger the action when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use the Windows runner for the job

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker (Windows runners should already have Docker pre-installed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (if pushing to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image with Maven
      - name: Build Docker image
        run: |
          docker build -t my-app-image .

      # Run tests in Docker container
      - name: Run tests in Docker container
        run: |
          docker run --rm my-app-image mvn test

      # Optionally, push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-app-image myusername/my-app-image:latest
          docker push myusername/my-app-image:latest
        if: success()  # Push only if the build is successful
